New additions (#3)
* packages

* chezmoi update

* added zsh

* no-colors

* no-colors

* why

* fix hyprpaper

* remove comment

* update hyprland to lua files

* quickshell fixes as well as theme fixes

diff --git a/install b/install
--- a/install
+++ b/install
@@ -18,10 +18,19 @@
 #
 # Built with <3 (and because I have done this too many times)
 # - jzlotek
+set -uex
+
+CWD=$(pwd)
 
 TMPDIR=$(mktemp -d)
+DOTS_BRANCH="${DOTS_BRANCH:-master}"
+GIT_REPO_RAW_FILE_URL="${GIT_REPO_RAW_FILE_URL:-https://raw.githubusercontent.com/jzlotek/dots/refs/heads/$DOTS_BRANCH}"
+DOTS_REPO="${DOTS_REPO:-git@github.com:jzlotek/dots.git}"
 CONFIG_DIR="${XDG_CONFIG_DIR:-$HOME/.config}"
-CWD=$(pwd)
+INSTALL_DIR="${XDG_DATA_HOME:-$HOME/.local/share}"
+SYNC="false"
+FULL="false"
+USERNAME="${USERNAME:-$(whoami)}"
 
 function cleanup() {
 	rm -r $TMPDIR
@@ -57,19 +66,51 @@ function check_pkg_installed() {
 }
 
 function install_yay() {
+	# the sudoers file has an includedir in /etc/sudoers.d/
+	# so we will create a temp no password for the wheel group
+	# then remove the file afterward
+	if [ $USERNAME = "root" ]; then
+		echo "Cannot install yay with root"
+		exit 1
+	fi
+
+	echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/tmp_wheel_nopasswd
+	trap 'rm /etc/sudoers.d/tmp_wheel_nopasswd -f' EXIT INT TERM
+
 	command -v yay >/dev/null && return
 	check_pkg_installed git
+	chmod 777 "${TMPDIR}"
 	pushd "${TMPDIR}" >/dev/null
-	git clone https://aur.archlinux.org/yay.git
+	sudo -u "${USERNAME}" git clone https://aur.archlinux.org/yay.git
 	pushd yay >/dev/null
-	makepkg -si
+
+	sudo -u "${USERNAME}" makepkg -si --noconfirm
+	rm /etc/sudoers.d/tmp_wheel_nopasswd -f
+
 	popd >/dev/null
 	popd >/dev/null
 }
 
+function setup_chaotic_aur() {
+	pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
+	pacman-key --lsign-key 3056513887B78AEB
+	pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' --noconfirm
+	pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm
+
+	if ! grep -q "/etc/pacman.d/chaotic-mirrorlist" "/etc/pacman.conf"; then
+		cat >> /etc/pacman.conf <<-EOF
+[chaotic-aur]
+Include = /etc/pacman.d/chaotic-mirrorlist
+EOF
+	fi
+
+}
+
 function install_ohmyzsh() {
-	ZSH="${CONFIG_DIR}/oh-my-zsh"
-	([ ! -d "${ZSH}" ] && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)")
+	export ZSH="${CONFIG_DIR}/oh-my-zsh"
+	if [ ! -d "${ZSH}" ]; then
+		sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
+	fi
 }
 
 function install_tmux() {
@@ -77,9 +118,112 @@ function install_tmux() {
 	ln -sf "${CONFIG_DIR}/tmux/tmux.conf" $HOME/.tmux.conf
 }
 
-SYNC="false"
-FULL="false"
-while getopts "shf" opt; do
+function sync_packages() {
+	if [ $(whoami) != root ]; then
+		echo "Can only sync packages as root"
+		exit 1
+	fi
+
+	sed -i "s/-j2/-j$(nproc)/;s/^#MAKEFLAGS/MAKEFLAGS/" /etc/makepkg.conf
+	sed -iE "s/^#?ParallelDownloads/ParallelDownloads = 10/" /etc/pacman.conf
+	sed -i "s/^#Color/Color/;s/^#ILoveCandy/ILoveCandy/" /etc/pacman.conf
+
+
+	pacman -Syy
+	pacman -S --needed archlinux-keyring --noconfirm
+	pacman -S --needed git curl --noconfirm
+	install_yay
+
+	packages_file=packages.csv
+	if [ ! -f "${packages_file}" ]; then
+		packages_file=$(mktemp "${TMPDIR}/packages.csv.XXX")
+		curl -o "${packages_file}" -L0 "${GIT_REPO_RAW_FILE_URL}/packages.csv"
+	fi
+	yay -Syy --needed --noconfirm >/dev/null $(sed -e 's/[[:blank:]]*#.*$//g' -e '/^[[:blank:]]*$/d' < "${packages_file}" | tr "\n" " " < "${packages_file}")
+}
+
+
+function install_dotfiles() {
+	set -eu
+
+	if ! chezmoi="$(command -v chezmoi)"; then
+		bin_dir="${HOME}/.local/bin"
+		chezmoi="${bin_dir}/chezmoi"
+		echo "Installing chezmoi to '${chezmoi}'" >&2
+		if command -v curl >/dev/null; then
+			chezmoi_install_script="$(curl -fsSL get.chezmoi.io)"
+		elif command -v wget >/dev/null; then
+			chezmoi_install_script="$(wget -qO- get.chezmoi.io)"
+		else
+			echo "To install chezmoi, you must have curl or wget installed." >&2
+			exit 1
+		fi
+		sh -c "${chezmoi_install_script}" -- -b "${bin_dir}"
+		unset chezmoi_install_script bin_dir
+	fi
+
+	# POSIX way to get script's dir: https://stackoverflow.com/a/29834779/12156188
+	script_dir="$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)"
+
+	set -- init --apply --source="${script_dir}"
+
+	echo "Running 'chezmoi $*'" >&2
+	"$chezmoi" init https://github.com/jzlotek/dots.git
+	if [ $DOTS_BRANCH != master ]; then
+		pushd $("$chezmoi" source-path) >/dev/null
+		"$chezmoi" git checkout $DOTS_BRANCH
+		popd >/dev/null
+	fi
+	"$chezmoi" apply --force
+}
+
+function bootstrap() {
+	setup_chaotic_aur
+	sync_packages
+}
+function prompt() {
+	read ${3:-} -p "$1 > " $2 </dev/tty
+}
+
+function setup_user() {
+	sed -i "s/^#\s*%wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/" /etc/sudoers
+
+	username=""
+	pass1=""
+	pass2=""
+
+	while [ -z "$username" ];do
+		prompt "Username" username
+	done
+	if grep -q "$username" /etc/passwd; then
+		echo $username
+		return
+	fi
+	while [ -z "$pass1" ];do
+		prompt "Password" pass1 -s
+	done
+	while [ "$pass1" != "$pass2" ]; do
+		prompt "Repeat Password" pass2 -s
+	done
+
+	grep -q "$username" /etc/passwd || useradd -m -G wheel "${username}" -s /bin/zsh
+	printf "%s\n%s\n" "$pass1" "$pass2" | passwd "$username"
+	unset pass1 pass2
+	echo $username
+}
+
+function install_all() {
+	check_pkg_installed git
+	check_pkg_installed curl
+	check_pkg_installed chezmoi
+
+	install_ohmyzsh
+	install_tmux
+
+	install_dotfiles
+}
+
+while getopts shf opt; do
 	case $opt in
 		s)
 			SYNC="true"
@@ -97,58 +241,18 @@ while getopts "shf" opt; do
 	esac
 done
 
+if [ "$(whoami)" = "root" ]; then
+	username=$(setup_user)
+	export USERNAME=$username
 
-function sync_packages() {
-	sudo pacman -Sy
-	sudo pacman -S --needed git --noconfirm
-	install_yay
-	yay -S --needed \
-		rsync \
-		git \
-		fzf \
-		openssh \
-		unzip \
-		neovim \
-		dmenu \
-		dunst \
-		tmux \
-		ttf-hack-nerd \
-		noto-fonts \
-		noto-fonts-cjk \
-		noto-fonts-emoji \
-		noto-fonts-extra \
-		wezterm-git \
-		hyprland \
-		wofi \
-		kitty \
-		waybar \
-		hyprpaper \
-		hyprlock \
-		xdg-desktop-portal-hyprland \
-		dunst \
-		pipewire \
-		wireplumber \
-		hyprpolkitagent \
-		colorz \
-		stow \
-		ghostty \
-		--noconfirm >/dev/null
-}
-
-
-[ $SYNC = "true" ] && sync_packages
-check_pkg_installed git
-check_pkg_installed rsync
-check_pkg_installed curl
-check_pkg_installed stow
-
-install_ohmyzsh
-
-install_tmux
-
-stow base nvim tmux scripts -t "${HOME}"
-
-if [ "${FULL}" = "true" ]; then
-	stow wm -t "${HOME}"
-	scripts/.local/bin/setbg wm/.config/hypr/wallpaper.png
+	bootstrap
+	sudo -u "$username" install_all
+	exit 0
+elif [ "${SYNC}" = "true" ]; then
+	export USERNAME=$(whoami)
+	sudo bootstrap
 fi
+
+install_all
+
+echo "Success"
